name: Python application

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        target:
          - aarch64-apple-darwin
          - x86_64-apple-darwin
        include:
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-apple-darwin
            os: macos-13

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: build
        run: pyinstaller -F pdf-splitter.py

      - name: package
        run: >
          zip --junk-paths
          pdf-splitter-${{ matrix.target }}.zip dist/pdf-splitter

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: pdf-splitter-${{ matrix.target }}
          path: pdf-splitter-${{ matrix.target }}.zip

  create-release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true
      - run: >
          echo '${{ steps.create-release.outputs.upload_url }}'
          > release_upload_url.txt
      - uses: actions/upload-artifact@v4
        with:
          name: create-release
          path: release_upload_url.txt

  upload-release:
    strategy:
      matrix:
        target:
          - aarch64-apple-darwin
          - x86_64-apple-darwin
    needs: [create-release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: create-release
      - id: upload-url
        run: |
          echo "url=$(cat release_upload_url.txt)" >> $GITHUB_OUTPUT
      - uses: actions/download-artifact@v4
        with:
          name: pdf-splitter-${{ matrix.target }}
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.upload-url.outputs.url }}
          asset_path: ./pdf-splitter-${{ matrix.target }}.zip
          asset_name: pdf-splitter-${{ matrix.target }}.zip
          asset_content_type: application/zip
